spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: yoke-kafka:9092

  datasource:
    url: jdbc:postgresql://yoke-postgres:5432/postgres
    
  zipkin:
    baseUrl: http://yoke-zipkin:9411    
    
logback:
  destination:
    url: yoke-logstash