spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}1747e10d9edbd134e86c135afd49248213930ec18dbafe8a44147e2745d74ce0'

  cloud:
    stream:
      bindings:
        addEventAttender:
          destination: yoke-add-event-attender          
          producer:
            partition-count: 3
        deleteEventAttender:
          destination: yoke-delete-event-attender
          producer:
            partition-count: 3

      kafka:
        binder:
          brokers: localhost:9092
          autoAddPartitions: true

server:
  port: 8584